### ISSUE TITLE
Not full height on Safari iOS. 

### ISSUE THREAD

**Issue by davydka** [qmixi/react-full-height#10]
![7AC11868-669E-46C1-B2E2-5EAAA2D6BA46](https://user-images.githubusercontent.com/1128500/69587567-be482200-0f9a-11ea-994f-daf853896edd.png)

**Comment by davydka** [comment]
iOS 12.4.1
iPhone XS

**Comment by qmixi** [comment]
@davydka thank you for reporting this.
Actually it was working properly, cause the first section had `startWidth={450}` property, which tells that section should be full-height from `450px` screen width.
You can read more about this prop under the following link: https://github.com/qmixi/react-full-height#make-your-full-height-section-responsive

I improved this demo anyway and you can see the changes under https://qmixi.github.io/react-full-height/demo/ url.

Currently, the first section doesn't use any extra parameters and I created a new one to present how `startWidth` parameter works.

![IMG_7856](https://user-images.githubusercontent.com/16977412/69612332-c56d3f80-102f-11ea-9bf1-f40d08d96b4d.PNG)
![IMG_7855](https://user-images.githubusercontent.com/16977412/69612333-c56d3f80-102f-11ea-9b71-fcb5a7fd1a62.PNG)

Thanks again for raising this issue ✌️
