### ISSUE TITLE
Doesn't work on Chrome iPhone

### ISSUE THREAD

**Issue by Izhaki** [qmixi/react-full-height#12]
On Chrome for iPhone instead of full width you get a scrollbar and the bottom is below the fold. You can see the scroll on this screenshot:

![no-full-height](https://user-images.githubusercontent.com/880132/74550785-dc923e00-4f49-11ea-8561-379358773ab0.jpeg)

To reproduce go to: https://su03u.csb.app/
And here's [the code](https://codesandbox.io/embed/crazy-wildflower-su03u?fontsize=14&hidenavigation=1&theme=dark)

This might be of interest: [The trick to viewport units on mobile](https://codesandbox.io/embed/crazy-wildflower-su03u?fontsize=14&hidenavigation=1&theme=dark)

**Comment by qmixi** [comment]
Hey @Izhaki, the reason is that the browser by default sets margin to the body element. All you need to do is to add reset styles:
```
body {
   margin: 0;
}
```
sandbox: https://codesandbox.io/s/wizardly-feynman-26cro?file=/src/styles.css
