### ISSUE TITLE
How to avoid double scroll on mobile?

### ISSUE THREAD

**Issue by shamoons** [qmixi/react-full-height#21]
In some cases, I have a double scroll on mobile. Specifically, the normal scroll of the full page and then scroll WITHIN the full height component.

**Comment by qmixi** [comment]
@shamoons you can add `canExceed` prop to your FullHeight component. Then it will exceed the height of the viewport, however, you'll eliminate the double scroll :) Let's check the https://qmixi.github.io/react-full-height/demo/ demo on the mobile :)

**Comment by shamoons** [comment]
If I do:
```
    <FullHeight
      canExceed={true}
      startWidth={1024}
    >
```

it doesn't quite fill:
![image](https://user-images.githubusercontent.com/1019677/96794956-3ac2cb00-13cd-11eb-8080-505c00e356de.png)

You can see the white space at the bottom

**Comment by qmixi** [comment]
@shamoons Basically, what the component does is adding css property:
```min-height: 100vh``` when `canExceed={true} prop is provided and 
```height: 100vh` when it's not.
Maybe there is a problem with adjusting the height of the child element and because of that, the white space occurs.  Unfortunately, I don't see the exact problem in your screenshot. If you could provide some example of your problem in the https://codesandbox.io/ or any other tool (which could allow me to see the whole code context), then it would be easier to help :)
